### ISSUE TITLE
你好 夏老师 请教thinkphp实战的博客问题

### ISSUE THREAD

**Issue by 312653161** [xialeistudio/thinkphp-inaction#11]
你写的这篇博客好难   我下载了代码 根本就运行不了  报错  SQLSTATE[HY000] [1049] Unknown database 'thinkphp_blog'     而且代码我看不懂  请教 怎么弄  怎么让他能运行  还有就是代码请教下您  我手机 158 2743 1390   微信也是这个 您加下

**Comment by 312653161** [comment]
请问  你们编辑部老师怎么联系

**Comment by xialeistudio** [comment]
请问你有php+mysql基础吗

**Comment by 312653161** [comment]
我qq  312653161     634732928 学过原生+sql 敲的不是太多

**Comment by xialeistudio** [comment]
了解过sql的话这个问题应该可以解决


发自我的 iPhone

**Comment by 312653161** [comment]
这个博客的难度  估计没有半个月难以摸透   html  css   js  这些前端就不看了   后端代码  还有各种配置    很难   我最早看一篇原生博客 我看了差不多20几天     不过那是我第一次看博客 而且 是基于文本的   没有这么多功能  而这篇博客  全是数据库的正删改查 我得慢慢想想  一个一个推敲

**Comment by 312653161** [comment]
不过看大神写的代码 看懂一次 比自己没脑子敲100次有帮助

**Comment by xialeistudio** [comment]
这个要脚踏实地去消化的，这样才能变成自己的东西，欲速则不达

发自我的 iPhone

**Comment by xialeistudio** [comment]
谢谢你的支持

发自我的 iPhone

**Comment by 312653161** [comment]
1博客本地运行很好  放网上路由就没效  admin/index/index无效  非要写index.php/admin/index/index
2这个类是做什么的     use Org\Net\Http;
3  这段看不懂   
$('#file').on('change', function(e) {
		//on就是bind
		if (e.target.files.length > 0) {
			var file = e.target.files[0];
			var xhr = new XMLHttpRequest();
			xhr.open('POST', '{:U("admin/index/upload")}', true);
			//这句话是来做ajax的   模板方法也能在js里面用 这句话才是真正的上传 我们是用表单post数据上传的 这里却是用js的ajax方法发送数据的
			var fd = new FormData;
			fd.append("file", file);
			xhr.onload = function(e) {
				var data = JSON.parse(xhr.responseText);
				$('.uploader #status').text('点击上传');
				if (data.error) {
					alert(data.error);
					return;
				}
				uploadCallback && uploadCallback(data.url);
			};//下面的代码也在29行if判断之内
			xhr.upload && (xhr.upload.onprogress = function(e) {
				if (e.lengthComputable) {
					$('.uploader #status').text('上传中(' + parseInt((e.loaded / e.total) * 100) + ')%');
				}
			});
			xhr.send(fd);
		}
	});

**Comment by xialeistudio** [comment]
1.百度Thinkphp隐藏index.php
2.Thinkphp提供的类
3.ajax上传文件

发自我的 iPhone

**Comment by 312653161** [comment]
IIS 服务器  Thinkphp隐藏index.php 怎么弄

**Comment by xialeistudio** [comment]
百度都有的，我不用IIS

发自我的 iPhone

**Comment by wumin198812** [comment]
请问后台账户和密码是???

**Comment by wumin198812** [comment]
请问后台账户和密码是???

**Comment by wumin198812** [comment]
请问后台账户和密码是???

**Comment by xialeistudio** [comment]
账号 admin 密码 111111
