### ISSUE TITLE
示例代码浏览时出现乱码，怎么解决？chapter-2

### ISSUE THREAD

**Issue by f43310** [xialeistudio/thinkphp-inaction#13]
璁剧疆鍓嶏細
Array
(
    [0] => Array
        (
            [id] => 1
            [username] => root
            [password] => root
        )

    [1] => Array
        (
            [id] => 2
            [username] => admin
            [password] => admin
        )

)
瑕嗙洊妯″紡璁剧疆鍚庯細
Array
(
    [0] => Array
        (
            [id] => 1
            [username] => root
            [password] => admin
        )

)
鍚堝苟妯″紡璁剧疆鍚庯細
Array
(
    [0] => Array
        (
            [id] => 1
            [username] => root
            [password] => root
        )

    [1] => Array
        (
            [id] => 2
            [username] => admin
            [password] => admin
        )

    [2] => Array
        (
            [id] => 1
            [username] => root
            [password] => admin
        )

)

**Comment by xialeistudio** [comment]
查看你的浏览器默认编码是什么，谷歌浏览器可以在右上角查看
