### ISSUE TITLE
留言板的问题

### ISSUE THREAD

**Issue by lgg9988** [xialeistudio/thinkphp-inaction#3]
当写入
```php
class MessageViewModel extends ViewModel
{
    public $viewFields = array(
        'Message' => array('message_id', 'content', 'created_at'),
        'User' => array('user_id', 'username', '_on' => 'User.user_id=Message.user_id')
    );
}
```
出现报错
1054:Unknown column 'User.user_id' in 'on clause' [ SQL语句 ] : SELECT COUNT(*) AS tp_count FROM message Message JOIN user User ON User.user_id=Message.user_id LIMIT 1

要怎样去决解

**Comment by xialeistudio** [comment]
你的数据表结构贴出来
执行SQL
`show create table user`

**Comment by xynetstudio** [comment]
CREATE TABLE `mb_user` (
  `user_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` varchar(40) NOT NULL,
  `password` char(32) NOT NULL,
  `created_at` int(10) NOT NULL,
  PRIMARY KEY (`user_id`),
  KEY `createdAt` (`created_at`) USING BTREE,
  KEY `username` (`username`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8
CREATE TABLE `mb_message` (
  `message_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `content` varchar(100) NOT NULL,
  `created_at` int(10) NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`message_id`),
  KEY `createdAt` (`created_at`) USING BTREE,
  KEY `userId` (`user_id`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8
报错：1064:You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' at line 1 [ SQL语句 ] : SELECT COUNT(*) AS tp_count FROM LIMIT 1

**Comment by xialeistudio** [comment]
```
SELECT COUNT(*) AS tp_count FROM LIMIT 1
```
SELECT语句的表名呢

**Comment by xynetstudio** [comment]
我完全是按照书本里的语句编写的，测试失败后，下载github里的源码，导入数据库后依然有问题，您可以自己测试一下试试

**Comment by xialeistudio** [comment]
麻烦把你照着书本里写的页码发出来
