### ISSUE TITLE
blog问题

### ISSUE THREAD

**Issue by codingkey** [xialeistudio/thinkphp-inaction#4]
{__NOLAYOUT__}
:(
invalid data source name
错误位置
FILE: D:\wamp64\www\blog\ThinkPHP\Library\Think\Db\Driver.class.php 　LINE: 109

**Comment by xialeistudio** [comment]
把你的数据库连接配置贴出来

发送自 Windows 10 版邮件应用

发件人: REGOUUI
发送时间: 2017年7月15日 20:11
收件人: xialeistudio/thinkphp-inaction
抄送: Subscribed
主题: [xialeistudio/thinkphp-inaction] blog问题 (#4)

{NOLAYOUT}
:(
invalid data source name
错误位置
FILE: D:\wamp64\www\blog\ThinkPHP\Library\Think\Db\Driver.class.php 　LINE: 109

**Comment by codingkey** [comment]
return array(
	'DB_TYPE' => 'mysql',
	'DB_DSN' => '127.0.0.1',
	'DB_uSER' => 'root',
	'DB_PWD' => 'root',
	'DB_PREFIX' => 'blog_',
	
);

**Comment by codingkey** [comment]
不好意思老师，发错了
return array(
	'DB_TYPE' => 'mysql',
	'DB_DSN' => '127.0.0.1',
	'DB_uSER' => 'root',
	'DB_PWD' => 'root',
	'DB_PREFIX' => 'blog_',
	'DB_PARAMS' => array(
		PDO::ATTR_CASE => PDO::CASE_NATURAL
	)
);

**Comment by xialeistudio** [comment]
大小写错误，DB_DSN改成DB_HOST

return array(
'DB_TYPE' => 'mysql',
'DB_HOST' => '127.0.0.1',
'DB_USER' => 'root',
'DB_PWD' => 'root',
'DB_PREFIX' => 'blog_',
);


发送自 Windows 10 版邮件应用

发件人: REGOUUI
发送时间: 2017年7月15日 23:54
收件人: xialeistudio/thinkphp-inaction
抄送: lei xia; Comment
主题: Re: [xialeistudio/thinkphp-inaction] blog问题 (#4)

return array(
'DB_TYPE' => 'mysql',
'DB_DSN' => '127.0.0.1',
'DB_uSER' => 'root',
'DB_PWD' => 'root',
'DB_PREFIX' => 'blog_',
);

**Comment by codingkey** [comment]
不好意思老师，我是个新手还在学习当中。看了您的书，刚刚您给出的答案又结合了教程上的已经解决了，现在我上传到服务器上以后。总是提示404 感觉好像是访问的时候出现了问题，
服务器上的错误提示
404 - 找不到文件或目录。
您要查找的资源可能已被删除，已更改名称或者暂时不可用。
本地测试错误提示
:(
无法加载控制器:Article
不知道该怎么修改，还请老师在百忙之中教教我谢谢

**Comment by xialeistudio** [comment]
windows服务器用得少
