### ISSUE TITLE
关于微信公众号的问题

### ISSUE THREAD

**Issue by wzcwmc** [xialeistudio/thinkphp-inaction#6]
![default](https://user-images.githubusercontent.com/26095245/29203404-24da9524-7ea3-11e7-918e-28e42907ae0a.png)
![default](https://user-images.githubusercontent.com/26095245/29203425-4ee75460-7ea3-11e7-8478-6e6604f3b3e2.png)
已经导入了ThinkWechat为什么一直还报错找不到

**Comment by xialeistudio** [comment]
1. 你的ThinkWechat导入到哪里了？
2. IndexController.class.php 代码贴出来

**Comment by wzcwmc** [comment]
![12343452](https://user-images.githubusercontent.com/26095245/29208947-b1765bce-7ebe-11e7-907b-04f368eb9b80.png)
![33333335307](https://user-images.githubusercontent.com/26095245/29208989-d525e3c8-7ebe-11e7-8597-c8b4f9f63071.png)

**Comment by xialeistudio** [comment]
ThinkWechat文件名改为ThinkWechat.class.php
