### ISSUE TITLE
关于博客的total

### ISSUE THREAD

**Issue by wzcwmc** [xialeistudio/thinkphp-inaction#7]
![default](https://user-images.githubusercontent.com/26095245/29203507-f04a5bb8-7ea3-11e7-9f8a-edc46cb1f078.png)
博客删除的时候total没有减少。。虽然我知道每次删除之后查询对应的categoryId  然后再把category里面的total让它每次自减1. 但是我不知道代码怎么加。怎么写

**Comment by xialeistudio** [comment]
`M('category')->where('id=5')->setDec('total',1);`

**Comment by wzcwmc** [comment]
id=5的话是不是就写死了。

**Comment by xialeistudio** [comment]
根据你的需要改
