### ISSUE TITLE
数据写入数据库全部正常，但是留言的内容没有在留言列表显示出来，翻页正常

### ISSUE THREAD

**Issue by dongqinliu** [xialeistudio/thinkphp-inaction#8]

**Comment by dongqinliu** [comment]
![default](https://user-images.githubusercontent.com/33278115/32264974-1314762a-bf1c-11e7-8196-9bcc0633f10c.jpg)

**Comment by xialeistudio** [comment]
代码贴出来，谢谢

**Comment by dongqinliu** [comment]
就是照着书打出来的，都没变动过

**Comment by dongqinliu** [comment]
<?php
namespace Home\Controller;
use Think\Controller;
use Think\Model;
use Think\Page;


class IndexController extends Controller {
  //检测登录
  private function checkLogin()
  {
    if(!session('user.userId')){
         $this->error('请登录',U('User/login'));
      }
  }
  //留言列表
  public function index(){
    $model = new \Home\Model\MessageViewModel();
    $count = $model->count();

    $page = new Page($count,1);
    $show = $page->show();
    $list = $model->order('message_id desc')->limit($page->firstRow.','.$page->listRows)->select;
    $this->assign('page',$show);
    $this->assign('list',$list);
    $this->display();
  }
  //发表留言
  public function post()
  {
    $this->checkLogin();
    $this->display();
  }
  //留言处理
  public function do_post()
  {
    $this->checkLogin();
    $content = I('content');
    if (empty($content)){
      $this->error('留言内容不能为空');
    }
    if (mb_strlen($content,'utf-8')>100){
      $this->error('留言内容最多100字');
    }

    $model = new Model('Message');
    $userId = session('user.userId');
    $data = array(
      'content' => $content,
      'created_at' => time(),
      'user_id' => $userId
    );
    if (!($model->create($data)&&$model->add())){
      $this->error('留言失败');
    }
    $this->success('留言成功',U('Index/index'));
  }
  public function delete()
  {
    $id = I('id');
    if (empty($id)){
      $this->error('缺少参数');
    }
    $this->checkLogin();
    $model = new Moedel('Message');
    if (!$model->where(array('message_id'=>$id,'user_id'=>session('user.userId')))->delete()){
      $this->error('删除失败');
    }
    $this->success('删除成功',U('index'));
  }
}

**Comment by dongqinliu** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>留言列表</title>
</head>
<body>
<h1>留言板</h1>

<div>
    <empty name="Think.session.user.username">
        <a href="{:U('User/login')}">登录</a>
        <a href="{:U('User/register')}">注册</a>
        <else/>
        欢迎您！ {$Think.session.user.username}         <a href="__URL__/post"><strong>发表留言</strong></a> <a href="{:U('User/logout')}">退出登录</a>
    </empty>
</div>
<volist name="list" id="item">
    <div>
        {$item.content}<br/>
        留言者：{$item.username}
        留言时间：{$item.created_at|date='Y-m-d H:i:s',###}
        <eq name="Think.session.user.userId" value="$item.user_id">
            <a href="{:U('delete?id='.$item['message_id'])}" onclick="return confirm('确定删除此条留言？')">删除</a>
        </eq>
    </div>
</volist>
<p>
    {$page}
</p>
</body>
</html>

**Comment by dongqinliu** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>留言列表</title>
</head>
<body>
<h1>留言板</h1>

<div>
    <empty name="Think.session.user.username">
        <a href="{:U('User/login')}">登录</a>
        <a href="{:U('User/register')}">注册</a>
        <else/>
        欢迎您！ {$Think.session.user.username}         <a href="__URL__/post"><strong>发表留言</strong></a> <a href="{:U('User/logout')}">退出登录</a>
    </empty>
</div>
<volist name="list" id="item">
    <div>
        {$item.content}<br/>
        留言者：{$item.username}
        留言时间：{$item.created_at|date='Y-m-d H:i:s',###}
        <eq name="Think.session.user.userId" value="$item.user_id">
            <a href="{:U('delete?id='.$item['message_id'])}" onclick="return confirm('确定删除此条留言？')">删除</a>
        </eq>
    </div>
</volist>
<p>
    {$page}
</p>
</body>
</html>

**Comment by dongqinliu** [comment]
[留言控制器.txt](https://github.com/xialeistudio/thinkphp-inaction/files/1434072/default.txt)
[index.html.txt](https://github.com/xialeistudio/thinkphp-inaction/files/1434073/index.html.txt)

**Comment by xialeistudio** [comment]
```
$list = $model->order('message_id desc')->limit($page->firstRow.','.$page->listRows)->select;
```
```
select后面的括号呢？下次不要再说照着书打了
```

**Comment by dongqinliu** [comment]
是我错，还有我另外想问一下，在这个留言板的基础上再实现通过邮箱找回密码这个功能，该怎么解决啊，网络上面已经找过了，但是还是不太懂

**Comment by xialeistudio** [comment]
1. 表单输入邮箱
2. action收到表单后，根据邮箱查询用户，如果没查到，直接报错到页面上
3. 如果查到了。生成一个随机字符串，并以该字符串作为**缓存key**,查出来的用户ID作为**缓存值**，写入缓存
4. 发送邮件，邮件访问链接为**重设密码的链接?token=刚才的随机字符串**
5. 点击进来重设密码的链接后，根据token查缓存，如果缓存失效，直接提示，邮件过期
6. 否则显示页面，提供两个密码输入框
7. 检测密码是否一致，然后根据缓存key读取用户ID，重设该用户密码。

**Comment by pensee8** [comment]
你好！bbs_post表在mysql中生成错误，能否提供一份在mysql中的thinkphp_bbs.sql. 谢谢！

**Comment by xialeistudio** [comment]
错误信息截图贴上来

**Comment by dongqinliu** [comment]
不好意思，由于是纯新手，我只做到了前2步，后面的可以给我代码看看吗

**Comment by xialeistudio** [comment]
根据上面的逻辑编码即可，直接提供代码对你有害无利
